eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8888/eureka/
    server:
      port: 8082

    spring:
      application:
        name: zlead-mall-protal
    #    url: jdbc:mysql://116.62.124.171:3306/zleadf?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #    username: zleadfuser
    #    password: zlfA#2019