eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8769
spring:
  application:
    name: zlead-mall-zuul
zuul:
  routes:
    api-a:
      path: /zlead-mall-admin/**
      service-id: zlead-mall-admin
    api-b:
      path: /zlead-mall-protal/**
      service-id: zlead-mall-protal
